name: Documentation

on: #(1)
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  page_build:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build documentation
        uses: mattnotmitt/doxygen-action@v1 #(2)
        with:
          doxyfile-path: ./Doxyfile #(3)
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3 #(4)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs #(5)
          commit_message: '[ci skip] ${{ github.event.head_commit.message }}' #(6)